### ISSUE TITLE
dist folder is empty

### ISSUE THREAD

**Issue by afeno** [jvdmr/mod_evasive#19]
I'm trying to install this version of evasive in order to whitelist some URLs.
But the dist folder is empty. Where is the .deb file?

**Comment by jvdmr** [comment]
Hi there!

You can find the .deb file on the Github [releases](https://github.com/jvdmr/mod_evasive/releases/tag/2.2.0) page.

It is generally considered bad practice to put files generated from source into source control, so that's why the installation package is kept separate from the source code.

Hope that helps!

**Comment by afeno** [comment]
Thank you for teaching me those best practices! This fork is really what I was looking for since a long time.
Great work!
